version: '3.8'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: wallet_movements
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: wallet
      PORT: 3000
    ports:
      - "3000:3000"
    depends_on:
      - db
    volumes:
      - .:/usr/src/app

  db:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: wallet
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
